workspaces:
  home_three_monitors:
    description: "Home 3 monitor setup"
    layout:
      - monitor: home_gn950@60
        position: origin
      - monitor: home_lg
        right_of: home_gn950@60
      - monitor: framework_screen
        below: home_gn950@60
    monitor_order:
      - framework_screen
      - home_gn950@60
      - home_lg

  office_three_monitors:
    description: "Office 3 monitor setup"
    layout:
      - monitor: office_lg
        position: origin
      - monitor: office_dell
        left_of: office_lg
      - monitor: framework_screen
        below: office_lg
    monitor_order:
      - framework_screen
      - office_lg
      - office_dell

  office_vertical:
    description: "Monitor over laptop (Office)"
    layout:
      - monitor: framework_screen
        position: origin
      - monitor: office_lg
        above: framework_screen
    monitor_order:
      - framework_screen
      - office_lg

  home_horizontal:
    description: "Monitor next to laptop (Home GN950)"
    layout:
      - monitor: home_gn950@60
        position: origin
      - monitor: home_lg
        right_of: home_gn950@60
    monitor_order:
      - home_gn950@60
      - home_lg

  home_horizontal_right:
    description: "Monitor next to laptop (Home GN950)"
    layout:
      - monitor: framework_screen
        position: origin
      - monitor: home_lg
        right_of: framework_screen
    monitor_order:
      - framework_screen
      - home_lg

  culmer_horizontal_builtin:
    description: "Monitor next to laptop (Culmer Small Dell)"
    layout:
      - monitor: culmer_small_dell
        position: origin
      - monitor: framework_screen
        right_of: culmer_small_dell
    monitor_order:
      - culmer_small_dell
      - framework_screen

  culmer_horizontal_2k:
    description: "Monitor next to laptop (Culmer 2K setup)"
    layout:
      - monitor: culmer_small_dell
        position: origin
      - monitor: culmer_dell_2k
        right_of: culmer_small_dell
    monitor_order:
      - culmer_small_dell
      - culmer_dell_2k

  salesforce_vertical:
    description: "Monitor over laptop (Salesforce)"
    layout:
      - monitor: framework_screen
        position: origin
      - monitor: salesforce_widescreen
        above: framework_screen
    monitor_order:
      - framework_screen
      - salesforce_widescreen

  default_laptop:
    description: "Default laptop mode"
    disable_others: true
    layout:
      - monitor: framework_screen
        position: origin
    monitor_order:
      - framework_screen
